package com.example.baoNgoCv.model.enums;

public enum NotificationType {

    NEW_APPLICATION,
    APPLICATION_UPDATED,

    INTERVIEW_INVITATION,
    APPLICATION_REJECTED,
    APPLICATION_ACCEPTED,
    INTERVIEW_RESCHEDULED,
    APPLICATION_REVIEWED,

    NEW_JOB_POSTING,
    JOB_CLOSED,
    JOB_EXPIRED,

    PASSWORD_CHANGED,
    NEW_DEVICE_LOGIN,

    EVENT_NOTIFICATION,
    DEADLINE_REMINDER,

    DOCUMENT_REQUEST,
    BACKGROUND_CHECK,

    SYSTEM_MAINTENANCE,
    POLICY_UPDATE,

    PROFILE_UPDATE,
    PROMOTION_NOTIFICATION,
    WELCOME,
    PLAN_UPGRADED,
    PLAN_DOWNGRADED,
    APPLICATION_WITHDRAWN
}
